import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { test } from "node:test";
import { finalizeFiles, produce } from "./build-private-local-diagnostics-artifact.mjs";

const commit = "a".repeat(40), sha = (v) => createHash("sha256").update(v).digest("hex"), bin = { paperclipai: "./dist/index.js", "paperclipai-local-diagnostics": "./dist/local-diagnostics.js" }, manifest = { name: "paperclipai", version: "0.3.1", description: "Paperclip CLI", license: "Apache-2.0", main: "./dist/index.js", types: "./dist/index.d.ts", files: ["dist", "README.md"], repository: { type: "git", url: "git+https://github.com/paperclipai/paperclip.git" }, engines: { node: ">=20" }, bin }, guarantees = { localOnly: true, centralInspected: false, centralContacted: false, centralStarted: false, centralRecovered: false, centralValidated: false, filesystemAccessed: false, environmentMutated: false, subprocessSpawned: false, networkAccessed: false, databaseOpened: false, storageOpened: false, telemetryInitialized: false, providersInitialized: false, pluginsLoaded: false, workersLoaded: false, schedulersLoaded: false, recoveryLoaded: false, serverStarted: false, persistentTimersInstalled: false, signalHandlersInstalled: false, repairsPerformed: false }, script = `#!/usr/bin/env node\nprocess.stdout.write(JSON.stringify({schemaVersion:"v1",command:"paperclipai-local-diagnostics",status:"ok",scope:{assessed:"diagnostic-runtime/build-compatibility",centralHealth:"not_assessed",centralLiveness:"not_assessed",centralReadiness:"not_assessed"},paperclip:{version:"0.3.1",buildCommit:"${commit}"},runtime:{nodeVersion:process.version,platform:process.platform,architecture:process.arch},checks:[{id:"build.metadata",status:"pass",code:"valid"},{id:"runtime.node",status:"pass",code:"supported"}],guarantees:${JSON.stringify(guarantees)}})+"\\n");`;
function fixture() { const root = mkdtempSync(join(tmpdir(), "producer-")), repo = join(root, "repo"), out = join(root, "out"), cli = join(repo, "cli"), dist = join(cli, "dist"), pkg = join(root, "package"); mkdirSync(out); mkdirSync(dist, { recursive: true }); mkdirSync(join(pkg, "dist"), { recursive: true }); for (const [name, value] of [["index.js", "#!/usr/bin/env node\n"], ["index.js.map", "{}"], ["local-diagnostics.js", script]]) { writeFileSync(join(dist, name), value); writeFileSync(join(pkg, "dist", name), value); } for (const base of [dist, join(pkg, "dist")]) { chmodSync(join(base, "index.js"), 0o755); chmodSync(join(base, "local-diagnostics.js"), 0o755); } writeFileSync(join(pkg, "README.md"), "readme\n"); for (const base of [cli, pkg]) writeFileSync(join(base, "package.json"), JSON.stringify(manifest)); return { root, repo, out, dist, pkg }; }
function deps(f, calls, fail = "") { return { repo: f.repo, lifecycle: async (input, { callback }) => { calls.push("lifecycle"); if (fail === "lifecycle") throw Error(); const tgz = join(input.stage, "paperclipai-0.3.1.tgz"); execFileSync("tar", ["-czf", tgz, "-C", f.root, "package/README.md", "package/dist/index.js", "package/dist/index.js.map", "package/dist/local-diagnostics.js", "package/package.json"]); await callback({ dist: f.dist, pack: { file: "pnpm", args: ["pack", "--json", "--pack-destination", input.stage], env: {} } }); return { source: { remote: "git@github.com:constant1n0/paperclip.git", ref: "refs/remotes/fork/master", commit, tree: "b".repeat(40) }, node: "v22.23.2", pnpm: "9.15.4", lockSha256: "c".repeat(64), acpxPatchSha256: "d".repeat(64) }; }, run: async (file, args, options) => { if (file === "paperclipai-local-diagnostics") { calls.push("smoke"); return { stdout: execFileSync(file, args, { cwd: options.cwd, env: options.env, encoding: "utf8" }), stderr: "" }; } calls.push("pack"); assert.equal(options.cwd, join(f.repo, "cli")); assert.deepEqual(args.slice(0, 3), ["pack", "--json", "--pack-destination"]); if (fail === "pack") throw Error(); return { stdout: JSON.stringify({ filename: join(args.at(-1), "paperclipai-0.3.1.tgz") }), stderr: "" }; } }; }
test("produces exactly the canonical five-file receipt and verification set", async () => { const f = fixture(), calls = []; try { const out = await produce({ commit, outDir: f.out }, deps(f, calls)); assert.equal(calls.join(","), "lifecycle,pack,smoke"); assert.match(out, /^\{"artifact_id":/); const files = readdirSync(f.out); assert.equal(files.length, 5); const verification = JSON.parse(readFileSync(join(f.out, files.find((name) => name.endsWith(".verification.json"))))); assert.equal(verification.package.manifestSha256, sha(JSON.stringify(manifest))); assert.equal(verification.artifact.bytes > 0, true); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("producer failures and occupied output leave no final files", async () => { for (const failure of ["lifecycle", "pack"]) { const f = fixture(); try { await assert.rejects(produce({ commit, outDir: f.out }, deps(f, [], failure))); assert.equal(readdirSync(f.out).length, 0); } finally { rmSync(f.root, { recursive: true, force: true }); } } });
test("rolls back every completed final rename in the five-file table", () => { for (let failAt = 0; failAt < 5; failAt += 1) { const renamed = [], removed = [], names = ["a.tgz", "a.receipt.json", "a.receipt.sha256", "a.verification.json", "a.verification.sha256"]; assert.throws(() => finalizeFiles("/out", "/stage", names, { assertAbsent() {}, lstatSync() { throw Error(); }, renameSync(_, to) { if (renamed.length === failAt) throw Error("rename"); renamed.push(to); }, rmSync(file) { removed.push(file); } })); assert.deepEqual(removed, renamed); } });
