import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { gunzipSync, gzipSync } from "node:zlib";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { test } from "node:test";
import { ARCHIVE_LIMITS, inspectStaticArchive, smokeTrustedArchive } from "./private-local-diagnostics-archive.mjs";

const commit = "a".repeat(40), hash = (x) => createHash("sha256").update(x).digest("hex"), bin = { paperclipai: "./dist/index.js", "paperclipai-local-diagnostics": "./dist/local-diagnostics.js" }, manifest = { name: "paperclipai", version: "0.3.1", description: "Paperclip CLI", license: "Apache-2.0", main: "./dist/index.js", types: "./dist/index.d.ts", files: ["dist", "README.md"], repository: { type: "git", url: "git+https://github.com/paperclipai/paperclip.git" }, engines: { node: ">=20" }, bin }, guarantees = { localOnly: true, centralInspected: false, centralContacted: false, centralStarted: false, centralRecovered: false, centralValidated: false, filesystemAccessed: false, environmentMutated: false, subprocessSpawned: false, networkAccessed: false, databaseOpened: false, storageOpened: false, telemetryInitialized: false, providersInitialized: false, pluginsLoaded: false, workersLoaded: false, schedulersLoaded: false, recoveryLoaded: false, serverStarted: false, persistentTimersInstalled: false, signalHandlersInstalled: false, repairsPerformed: false };
const script = `#!/usr/bin/env node\nprocess.stdout.write(JSON.stringify({schemaVersion:"v1",command:"paperclipai-local-diagnostics",status:"ok",scope:{assessed:"diagnostic-runtime/build-compatibility",centralHealth:"not_assessed",centralLiveness:"not_assessed",centralReadiness:"not_assessed"},paperclip:{version:"0.3.1",buildCommit:"${commit}"},runtime:{nodeVersion:process.version,platform:process.platform,architecture:process.arch},checks:[{id:"build.metadata",status:"pass",code:"valid"},{id:"runtime.node",status:"pass",code:"supported"}],guarantees:${JSON.stringify(guarantees)}})+"\\n");`;
function fixture(change = () => {}) { const root = mkdtempSync(join(tmpdir(), "archive-")), pkg = join(root, "package"), dist = join(pkg, "dist"); mkdirSync(dist, { recursive: true }); writeFileSync(join(pkg, "README.md"), "readme\n"); writeFileSync(join(pkg, "package.json"), JSON.stringify(manifest)); writeFileSync(join(dist, "index.js"), "#!/usr/bin/env node\n"); writeFileSync(join(dist, "index.js.map"), "{}"); writeFileSync(join(dist, "local-diagnostics.js"), script); chmodSync(join(dist, "index.js"), 0o755); chmodSync(join(dist, "local-diagnostics.js"), 0o755); change({ root, pkg, dist }); const tgz = join(root, "fixture.tgz"), paths = ["package/README.md", "package/dist/index.js", "package/dist/index.js.map", "package/dist/local-diagnostics.js", "package/package.json"]; execFileSync("tar", ["-czf", tgz, "-C", root, ...paths]); const bytes = readFileSync(tgz); return { root, bytes, expected: { "dist/index.js": hash(readFileSync(join(dist, "index.js"))), "dist/local-diagnostics.js": hash(readFileSync(join(dist, "local-diagnostics.js"))) }, manifest: hash(readFileSync(join(pkg, "package.json"))) }; }
const anchors = (f) => ({ expectedDistSha256: f.expected, expectedManifestSha256: f.manifest, expectedArtifactSha256: hash(f.bytes) });
function header(name, data = "x", type = "0") { const b = Buffer.alloc(512); b.write(name); b.write("0000644\0", 100); b.write(`${data.length.toString(8).padStart(11, "0")}\0`, 124); b.fill(32, 148, 156); b.write(type, 156); b.write("ustar\0", 257); const sum = [...b].reduce((a, n) => a + n, 0); b.write(`${sum.toString(8).padStart(6, "0")}\0 `, 148); return Buffer.concat([b, Buffer.from(data), Buffer.alloc((512 - data.length % 512) % 512)]); }
function bad(...items) { return gzipSync(Buffer.concat([...items.map(([n, t = "0"]) => header(n, "x", t)), Buffer.alloc(1024)])); }

test("static inspection accepts a full manifest without executing diagnostic bytes", () => { const f = fixture(({ root, dist }) => writeFileSync(join(dist, "local-diagnostics.js"), `#!/usr/bin/env node\nimport{writeFileSync}from"node:fs";writeFileSync(${JSON.stringify(join(root, "sentinel"))},"x")`)); try { const out = inspectStaticArchive(f.bytes, anchors(f)); assert.equal(out.package.manifestSha256, f.manifest); assert.equal(existsSync(join(f.root, "sentinel")), false); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("trusted smoke requires anchors and executes exactly once after static validation", async () => { const f = fixture(), calls = []; try { const out = await smokeTrustedArchive(f.bytes, { commit, ...anchors(f) }, { run: async (file, args, options) => { calls.push([file, args]); return { stdout: execFileSync(file, args, { cwd: options.cwd, env: options.env, encoding: "utf8" }), stderr: "" }; } }); assert.equal(out.diagnostics.commit, commit); assert.equal(calls.length, 1); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("static inspection rejects hash, archive, manifest, bin, and shebang deviations", async () => { const f = fixture(); try { for (const bytes of [bad(["package/../x"]), Buffer.concat([f.bytes, Buffer.from("x")]), Buffer.alloc(ARCHIVE_LIMITS.compressed + 1)]) assert.throws(() => inspectStaticArchive(bytes, { ...anchors(f), expectedArtifactSha256: hash(bytes) }), /A_/); for (const change of [({ pkg }) => writeFileSync(join(pkg, "package.json"), JSON.stringify({ ...manifest, scripts: { install: "node x" } })), ({ pkg }) => writeFileSync(join(pkg, "package.json"), JSON.stringify({ ...manifest, bin: { paperclipai: "./wrong.js" } }))]) { const invalid = fixture(change); assert.throws(() => inspectStaticArchive(invalid.bytes, anchors(invalid)), /A_PACKAGE/); rmSync(invalid.root, { recursive: true, force: true }); } const shebang = fixture(({ dist }) => writeFileSync(join(dist, "index.js"), "x")); assert.throws(() => inspectStaticArchive(shebang.bytes, anchors(shebang)), /A_EXEC/); rmSync(shebang.root, { recursive: true, force: true }); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("static snapshot remains isolated from caller mutation", () => { const f = fixture(); try { const original = Buffer.from(f.bytes), out = inspectStaticArchive(f.bytes, anchors(f)); f.bytes.fill(0); assert.equal(out.sha256, hash(original)); } finally { rmSync(f.root, { recursive: true, force: true }); } });
