import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { gunzipSync, gzipSync } from "node:zlib";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { test } from "node:test";
import { ARCHIVE_LIMITS, inspectArchive } from "./private-local-diagnostics-archive.mjs";

const commit = "a".repeat(40), hash = (x) => createHash("sha256").update(x).digest("hex"), bin = { paperclipai: "./dist/index.js", "paperclipai-local-diagnostics": "./dist/local-diagnostics.js" }, guarantees = { localOnly: true, centralInspected: false, centralContacted: false, centralStarted: false, centralRecovered: false, centralValidated: false, filesystemAccessed: false, environmentMutated: false, subprocessSpawned: false, networkAccessed: false, databaseOpened: false, storageOpened: false, telemetryInitialized: false, providersInitialized: false, pluginsLoaded: false, workersLoaded: false, schedulersLoaded: false, recoveryLoaded: false, serverStarted: false, persistentTimersInstalled: false, signalHandlersInstalled: false, repairsPerformed: false };
const script = `#!/usr/bin/env node\nprocess.stdout.write(JSON.stringify({schemaVersion:"v1",command:"paperclipai-local-diagnostics",status:"ok",scope:{assessed:"diagnostic-runtime/build-compatibility",centralHealth:"not_assessed",centralLiveness:"not_assessed",centralReadiness:"not_assessed"},paperclip:{version:"0.3.1",buildCommit:"${commit}"},runtime:{nodeVersion:process.version,platform:process.platform,architecture:process.arch},checks:[{id:"build.metadata",status:"pass",code:"valid"},{id:"runtime.node",status:"pass",code:"supported"}],guarantees:${JSON.stringify(guarantees)}})+"\\n");`;
function fixture(change = () => {}) { const root = mkdtempSync(join(tmpdir(), "archive-")), pkg = join(root, "package"), dist = join(pkg, "dist"); mkdirSync(dist, { recursive: true }); writeFileSync(join(pkg, "README.md"), "readme\n"); writeFileSync(join(pkg, "package.json"), JSON.stringify({ name: "paperclipai", version: "0.3.1", bin })); writeFileSync(join(dist, "index.js"), "#!/usr/bin/env node\n"); writeFileSync(join(dist, "index.js.map"), "{}"); writeFileSync(join(dist, "local-diagnostics.js"), script); chmodSync(join(dist, "index.js"), 0o755); chmodSync(join(dist, "local-diagnostics.js"), 0o755); change({ root, pkg, dist }); const tgz = join(root, "fixture.tgz"), paths = ["package/README.md", "package/dist/index.js", "package/dist/index.js.map", "package/dist/local-diagnostics.js", "package/package.json"]; execFileSync("tar", ["-czf", tgz, "-C", root, ...paths]); const bytes = readFileSync(tgz); return { root, bytes, expected: { "dist/index.js": hash(readFileSync(join(dist, "index.js"))), "dist/local-diagnostics.js": hash(readFileSync(join(dist, "local-diagnostics.js"))) } }; }
function header(name, data = "x", type = "0") { const b = Buffer.alloc(512); b.write(name); b.write("0000644\0", 100); b.write(`${data.length.toString(8).padStart(11, "0")}\0`, 124); b.fill(32, 148, 156); b.write(type, 156); b.write("ustar\0", 257); const sum = [...b].reduce((a, n) => a + n, 0); b.write(`${sum.toString(8).padStart(6, "0")}\0 `, 148); return Buffer.concat([b, Buffer.from(data), Buffer.alloc((512 - data.length % 512) % 512)]); }
function bad(...items) { return gzipSync(Buffer.concat([...items.map(([n, t = "0"]) => header(n, "x", t)), Buffer.alloc(1024)])); }
test("RED: matching trusted dist hashes run the real synthetic archive", async () => { const f = fixture(); try { const out = await inspectArchive(f.bytes, { commit, expectedDistSha256: f.expected }); assert.equal(out.diagnostics.commit, commit); assert.equal(out.sha256, hash(f.bytes)); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("RED: mismatched trust anchors, bounded inputs, and canonical tar violations fail before smoke", async () => { const f = fixture(), sentinel = join(f.root, "sentinel"); try { const evil = fixture(({ dist }) => writeFileSync(join(dist, "local-diagnostics.js"), `#!/usr/bin/env node\nimport{writeFileSync}from"node:fs";writeFileSync(${JSON.stringify(sentinel)},"x")`)); await assert.rejects(inspectArchive(evil.bytes, { commit, expectedDistSha256: f.expected }), /A_TRUST/); assert.equal(existsSync(sentinel), false); rmSync(evil.root, { recursive: true, force: true }); for (const bytes of [bad(["package/../x"]), bad(["package/x", "2"]), bad(["package/README.md"], ["package/README.md"]), Buffer.concat([f.bytes, Buffer.from("x")])]) await assert.rejects(inspectArchive(bytes, { commit, expectedDistSha256: f.expected }), /A_/); await assert.rejects(inspectArchive(Buffer.alloc(ARCHIVE_LIMITS.compressed + 1), { commit, expectedDistSha256: f.expected }), /A_LIMIT/); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("RED: accepts one real gzip member but rejects invalid trailers, members, and tar padding", async () => { const f = fixture(); try { const decoded = gunzipSync(f.bytes), padded = Buffer.from(decoded), at = padded.indexOf(Buffer.from("readme\n")); padded[at + 7] = 1; const crc = Buffer.from(f.bytes), size = Buffer.from(f.bytes); crc[crc.length - 8] ^= 1; size[size.length - 1] ^= 1; for (const bytes of [Buffer.concat([f.bytes, f.bytes]), gzipSync(padded), crc, size]) await assert.rejects(inspectArchive(bytes, { commit, expectedDistSha256: f.expected }), /A_ARCHIVE/); } finally { rmSync(f.root, { recursive: true, force: true }); } });
test("RED: package/executable/complete diagnostic contract and snapshot isolation fail closed", async () => { const cases = [["package", ({ pkg }) => writeFileSync(join(pkg, "package.json"), "{}")], ["mode", ({ dist }) => chmodSync(join(dist, "index.js"), 0o644)], ["shebang", ({ dist }) => writeFileSync(join(dist, "index.js"), "x")], ["stderr", ({ dist }) => writeFileSync(join(dist, "local-diagnostics.js"), "#!/usr/bin/env node\nprocess.stderr.write('x')")], ["health", ({ dist }) => writeFileSync(join(dist, "local-diagnostics.js"), script.replace('"centralStarted":false', '"centralStarted":true'))], ["commit", ({ dist }) => writeFileSync(join(dist, "local-diagnostics.js"), script.replace(commit, "b".repeat(40)))]]; for (const [, change] of cases) { const f = fixture(change); try { await assert.rejects(inspectArchive(f.bytes, { commit, expectedDistSha256: f.expected }), /A_/); } finally { rmSync(f.root, { recursive: true, force: true }); } } const f = fixture(); try { const original = Buffer.from(f.bytes), promise = inspectArchive(f.bytes, { commit, expectedDistSha256: f.expected }); f.bytes.fill(0); assert.equal((await promise).sha256, hash(original)); } finally { rmSync(f.root, { recursive: true, force: true }); } });
