import assert from "node:assert/strict";
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { inspectAcpx, withBuildLifecycle } from "./private-local-diagnostics-build-lifecycle.mjs";

const sha = "a".repeat(40), tree = "b".repeat(40), hash = "x3fethhotv43zektyl5prdwf54";
function fixture() { const repo = mkdtempSync(join(tmpdir(), "lifecycle-")), acpx = join(repo, "packages", "adapter-utils", "node_modules", "acpx"); mkdirSync(join(repo, "cli")); mkdirSync(join(acpx, "dist"), { recursive: true }); mkdirSync(join(repo, "node_modules")); writeFileSync(join(repo, "pnpm-lock.yaml"), `patchedDependencies:\n  acpx@0.12.0:\n    hash: ${hash}\n    path: patches/acpx@0.12.0.patch\nacpx@0.12.0(patch_hash=${hash}):\n`); writeFileSync(join(repo, "node_modules", ".modules.yaml"), `acpx@0.12.0(patch_hash=${hash}):`); writeFileSync(join(repo, "patches-acpx"), "patch"); writeFileSync(join(acpx, "package.json"), '{"name":"acpx","version":"0.12.0"}'); for (const name of ["runtime.d.ts", "runtime.js", "live-checkpoint-x.js"]) writeFileSync(join(acpx, "dist", name), "spawnCwd onAgentSpawn"); writeFileSync(join(repo, "cli", "package.json"), "original"); chmodSync(join(repo, "cli", "package.json"), 0o640); return repo; }
function runner(calls, fail = "") { return async (file, args, opts) => { calls.push({ file, args, env: opts.env?.COREPACK_ENABLE_NETWORK, pc: opts.env?.PC_BUILD_COMMIT }); const key = `${file} ${args.join(" ")}`; if (key === fail) throw new Error("token=secret"); if (args[0] === "rev-parse" && args[1].endsWith("^{tree}")) return { stdout: `${tree}\n` }; if (key === "git rev-parse HEAD") return { stdout: `${sha}\n` }; if (key === "git rev-parse refs/remotes/fork/master") return { stdout: `${sha}\n` }; if (key === "git config --get remote.fork.url") return { stdout: "git@github.com:constant1n0/paperclip.git\n" }; if (key === "git status --porcelain") return { stdout: "" }; if (key === "node --version") return { stdout: "v22.23.2\n" }; if (key === "pnpm --version") return { stdout: "9.15.4\n" }; return { stdout: "" }; }; }
test("runs exact offline install, workspace smoke, typecheck, and build then restores mutable files", async () => { const repo = fixture(), calls = []; const out = await withBuildLifecycle({ repo, commit: sha, patch: "patches-acpx" }, { run: runner(calls), callback: async () => { writeFileSync(join(repo, "cli", "package.json"), "built"); writeFileSync(join(repo, "cli", "package.dev.json"), "new"); writeFileSync(join(repo, "cli", "README.md"), "new"); mkdirSync(join(repo, "cli", "dist")); } }); assert.equal(readFileSync(join(repo, "cli", "package.json"), "utf8"), "original"); assert.equal(existsSync(join(repo, "cli", "package.dev.json")), false); assert.equal(existsSync(join(repo, "cli", "dist")), false); const run = calls.filter(({ file }) => file !== "git" && file !== "node"); assert.deepEqual(run.map(({ file, args }) => `${file} ${args.join(" ")}`), ["pnpm --version", "pnpm install --offline --frozen-lockfile --ignore-scripts", "pnpm exec vitest run packages/adapter-utils/src/acpx-engine/remote-spawn-smoke.test.ts", "pnpm -r typecheck", "bash scripts/build-npm.sh --skip-typecheck"]); assert.equal(run[1].env, "0"); assert.equal(run.at(-1).pc, sha); assert.equal(out.acpx.path, "packages/adapter-utils/node_modules/acpx"); });
test("fails closed on ACPX workspace evidence and lifecycle errors", async () => { const broken = fixture(); writeFileSync(join(broken, "packages", "adapter-utils", "node_modules", "acpx", "package.json"), '{"name":"acpx","version":"0.12.1"}'); assert.throws(() => inspectAcpx(broken, readFileSync(join(broken, "pnpm-lock.yaml"), "utf8")), /L_ACPX/); for (const kind of ["pnpm install --offline --frozen-lockfile --ignore-scripts", "pnpm exec vitest run packages/adapter-utils/src/acpx-engine/remote-spawn-smoke.test.ts", "pnpm -r typecheck", "bash scripts/build-npm.sh --skip-typecheck"]) { const repo = fixture(); await assert.rejects(withBuildLifecycle({ repo, commit: sha, patch: "patches-acpx" }, { run: runner([], kind) }), /L_EXEC: command failed/); } });
